# Settings for the motd (Message of the Day) in the server list.
motd:
  # Enable this?
  enabled: true
  # List of MOTD's to display. Each line is a new MOTD.
  # A MOTD (Message of the Day) is a message that is displayed to users in the server list.
  list:
    - "&7Welcome to &b&lMyServer&7!%newline%&7Join &4&lNOW&7."
    - "&7We have &b&l%motd_online%&7/&b&l%motd_max% &7players online!%newline%&7Join &4&lNOW&7."
  # The way the MOTD is selected.
  # Options:
  # RANDOM: Select a random MOTD from the list.
  # SEQUENTIAL: Select the next MOTD in the list.
  selection: RANDOM
  # The amount of server ticks to wait before selecting the next single line for the message of the day.
  ticks: 20

# Settings for the sample in the server list.
sample:
  # Enable this?
  enabled: true
  # List of samples to display. Each line is a new sample.
  # A sample is what you see when you hover over the server's ping in the server list.
  list:
    - "&9Website&7: &bhttps://example.com%newline%&9Discord&7: &bhttps://discord.gg/example"
    - "&9Website&7: &bhttps://example.com%newline%&9Discord&7: &bhttps://discord.gg/example%newline%&9Store&7: &bhttps://example.com/store"
  # The way the sample is selected.
  # Options:
  # RANDOM: Select a random line from the list.
  # SEQUENTIAL: Select the next line in the list.
  selection: RANDOM
  # The amount of server ticks to wait before selecting the next single line for the sample.
  ticks: 20

# Settings for the player count in the server list.
online:
  # The maximum number of players to display in the MOTD.
  # You can put any equation here.
  max: "100"
  # max: "100 + 50"
  # max: "100 + %motd_online%"
  # The number of online players to display in the MOTD.
  # You can put any equation here.
  current: "%streamline_players_online%"
  # current: "%streamline_players_online% + 10"

# The version of your server when players are connecting.
version:
  # Enable this?
  enabled: false
  # The name.
  name: "1.19.3"
  # The specific protocol version.
  protocol: 757